### ISSUE TITLE
Open dropdown keep items in center

### ISSUE THREAD

**Issue by jntagadiad** [diegoveloper/flutter_direct_select#10]
Is it possible to implement that the items on this dropdown will be on the center of the screen, not in the exact place of the dropdown?

**Comment by diegoveloper** [comment]
Hmm it will break the design of 'direct select' , so i think is possible
but is not recommended to implement

**Comment by jntagadiad** [comment]
I want to achieve that the position of the dropdown is in the appbar. I was worrying what if the items are too long I cant scroll enough to the top

**Comment by diegoveloper** [comment]
Yeah, this component is useful in some situations , probably it won't work
well on the appbar position.

**Comment by jntagadiad** [comment]
Okay sir. thanks a lot
