### ISSUE TITLE
setState in onItemSelectedListener

### ISSUE THREAD

**Issue by jntagadiad** [diegoveloper/flutter_direct_select#11]
When I using onItemSelectedListener I cant use setState.

**Comment by diegoveloper** [comment]
Add minimum code to reproduce the issue.

**Comment by jntagadiad** [comment]
Sorry, when using setState the was updated but the list was not updated

**Comment by diegoveloper** [comment]
Check the sample https://github.com/diegoveloper/flutter_direct_select/blob/master/example/lib/main.dart
