### ISSUE TITLE
Can not open dropdown list on item select.

### ISSUE THREAD

**Issue by shrutikateiosys** [diegoveloper/flutter_direct_select#4]
its not user interactive to press up & down. kindly help to give us ontap functionality on it.

**Comment by diegoveloper** [comment]
Sorry, if you check the README file that's the purpose of this package, reduce the user interaction otherwise you can just use the `DropdownButton` out of the box in Flutter.

https://api.flutter.dev/flutter/material/DropdownButton-class.html
