### ISSUE TITLE
this code shows an error <<  ScrollController not attached to any scroll views. >>

### ISSUE THREAD

**Issue by anexasp** [diegoveloper/flutter_direct_select#5]
This code shows an error <<  ScrollController not attached to any scroll views. >>

**Comment by diegoveloper** [comment]
which code? Could you add a minimum sample to reproduce the issue?

**Comment by anexasp** [comment]
I copied pasted the example from the code here [LINK](https://github.com/diegoveloper/flutter_direct_select/blob/master/example/lib/main.dart) and ran into the ScrollController error.

thanks.

**Comment by diegoveloper** [comment]
Thanks for report the issue, I'm fixing it now

**Comment by anexasp** [comment]
Awesome, thanks :)

**Comment by diegoveloper** [comment]
Check the new version: `1.0.1` ,  don't forget `flutter pub upgrade`

**Comment by anexasp** [comment]
Great !! version 1.0.1 seems to have resolved the earlier problem, however there is another problem showing up now (comments as below). Is this as well related: 
<<<
The method 'reverse' was called on null.
Receiver: null
Tried calling: reverse(Instance of 'OverlayEntry')
>>>

**Comment by diegoveloper** [comment]
is the issue happens with the same sample code? or are you using other code?

**Comment by anexasp** [comment]
same sample code in the [LINK](https://github.com/diegoveloper/flutter_direct_select/blob/master/example/lib/main.dart).

**Comment by diegoveloper** [comment]
hmm I can't reproduce the issue, could you attach a video? what are the steps to reproduce the issue ? are you on stable version (flutter)?

**Comment by diegoveloper** [comment]
I published a new version : https://pub.dev/packages/direct_select/versions/1.0.2+1 ,  I can't reproduce your issue yet. In you can reproduce it, please open a new issue. Thanks!!

**Comment by anexasp** [comment]
Perfect !!. i updated the dependencies to 1.0.2, changed channel to master and voila ... it works.
thanks for your patience and immediate response :)
